version: '2.0'
services:
    php:
        build: .
        container_name: app
        restart: unless-stopped
        env_file:
            - .env
        ports:
            - "80:80"
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./deploy/local.ini:/usr/local/etc/php/local.ini
            - ./deploy/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network
        depends_on:
            -   db
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
            MARIADB_DATABASE: reo.test
            MYSQL_ROOT_USERNAME: root
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
